# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  proj_01_name: 'Bifrost.Core'
  proj_01_src: 'src/$(proj_01_name)'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  name: 'build_01'
  displayName: 'Build - 01 - $(proj_01_name)'
  continueOnError: false
  inputs:
      command: 'build'
      projects: '$(proj_01_src)/$(proj_01_name).csproj'
      arguments: '--verbosity m --configuration $(BuildConfiguration) --output $(Build.StagingDirectory)/$(proj_01_name)'
      # q[uiet], m[inimal], n[ormal], d[etailed], and diag[nostic]

- task: ArchiveFiles@2
  name: 'zip_01'
  displayName: 'Archive - 01 - $(proj_01_name)'
  continueOnError: false
  inputs:
      archiveType: 'zip'
      includeRootFolder: false
      rootFolderOrFile: '$(Build.StagingDirectory)/$(proj_01_name)'
      archiveFile: '$(publish_path)/$(proj_01_name).zip'
      replaceExistingArchive: true
      quiet: true

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: "Automation Tests"
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\Automation.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    runTestsInIsolation: true
    codeCoverageEnabled: true
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'